services:
  - docker

before_install: 
  - docker build -t victor0719/react-test -f ./client/Dockerfile.dev ./client
  
script: 
  - docker run -e CI=true victor0719/react-test npm run test

after_success: 
  - docker build -t victor0719/multi-client ./client
  - docker build -t victor0719/multi-nginx ./nginx
  - docker build -t victor0719/multi-server ./server
  - docker build -t victor0719/multi-worker ./worker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push victor0719/multi-client
  - docker push victor0719/multi-nginx
  - docker push victor0719/multi-server
  - docker push victor0719/multi-worker

deploy:
  provider: elasticbeanstalk
  region: 'eu-north-1'
  app: 'multi-docker'
  env: 'Multi-docker-env'
  bucket_name: 'elasticbeanstalk-eu-north-1-637423464841'
  bucket_path: 'docker-multi'
  on:
    branch: main
  access-key-id: $AWS_ACCESS_KEY
  secret-access-key: "$AWS_SECRET_KEY"