version: "3.8"
services:
  client:
    image: "victor0719/multi-client"
    mem_limit: 128m
    hostname: client
  server:
    image: "victor0719/multi-server"
    mem_limit: 128m
    hostname: api
    environment:
      - REDIS_URL=$REDIS_URL
      - PGUSER=$PGUSER
      - PGHOST=$PGHOST
      - PGDATABASE=$PGDATABASE
      - PGPASSWORD=$PGPASSWORD
      - PGPORT=$PGPORT
  worker:
    image: "victor0719/multi-worker"
    mem_limit: 128m
    hostname: worker
    environment:
      - REDIS_URL=$REDIS_URL
  nginx:
    image: "victor0719/multi-nginx"
    mem_limit: 128m
    hostname: nginx
    ports:
      - "80:80"